### ISSUE TITLE
Great job, but how did you get rounded corners?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [bluebyt/Wayfire-dots#1]
Absolutely love the rice, one of the best I have ever seen!
Definitely the best wayfire rice.
Question, how did you get rounded corners?

**Comment by bluebyt** [comment]
I use mainly GTK4 apps, they have all rounded corner.
Like blackbox terminal, Nautilus, image viewer is loupe, clapper video player, gnome-text-editor...
Unfortunately they have not all rounded corner like Brave browser.

**Comment by ItsTerm1n4l** [comment]
Oops, forgot to close.
