### ISSUE TITLE
How to Install Pixdecor exactly?

### ISSUE THREAD

**Issue by DarkevilPT** [bluebyt/Wayfire-dots#3]
```
git clone https://github.com/WayfireWM/wf-install
cd pixdecor
PKG_CONFIG_PATH=/opt/wayfire/lib/pkgconfig meson setup build --prefix=/opt/wayfire
ninja -C build
ninja -C build install
```
I cant find any pixdecor inside wf-install.
How exactly can we make that amazing theme to happen on wayfire?

**Comment by DarkevilPT** [comment]
I believe this is the missing correct code from the readme I assume?


https://github.com/soreau/pixdecor.git
cd pixdecor
PKG_CONFIG_PATH=/opt/wayfire/lib/pkgconfig meson setup build --prefix=/opt/wayfire
ninja -C build
ninja -C build install

**Comment by bluebyt** [comment]
My mistake, Thank you for pointing that out,  I will correct the line:
```
git clone https://github.com/soreau/pixdecor.git
```

**Comment by bluebyt** [comment]
Fixed the instruction for pixdecor
